name: Build OrangeFox gtexslet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install basic deps
        run: |
          sudo apt update
          sudo apt install -y git curl python3

      - name: Setup repo tool
        run: |
          mkdir -p $HOME/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
          chmod +x $HOME/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init source (test only)
        run: |
          mkdir test
          cd test
          repo init -u https://github.com/OrangeFoxRecovery/Manifest.git -b fox_7.1
